apiVersion: v2
name: helm-charts-oci-proxy
description: Transparently proxy and transform Chart Repository styled Helm Charts as OCI artifacts. Now you can address any public Chart Repository styled Helm Chart as an OCI image.
type: application
version: 1.0.0
appVersion: "latest"
home: https://github.com/container-registry/helm-charts-oci-proxy
icon: https://avatars.githubusercontent.com/u/46576199?s=200&v=4
keywords:
  - Helm Proxy
  - OCI Proxy
  - Helm Chart Proxy
sources:
  - https://github.com/container-registry/helm-charts-oci-proxy
maintainers:
  - name: 8gears Container Registry

#annotations:
#  artifacthub.io/changes:



