name: "Publish Chart"

on:
  pull_request:
    paths:
      - .github/workflows/publish_chart.yml
      - chart/**
  push:
    paths:
      - .github/workflows/publish_chart.yml
      - chart/**
    branches:
      - main

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    outputs:
      CHART_VERSION: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version Helm Chart
        id: version
        uses: codacy/git-version@2.5.4
        with:
          prefix: chart-
          log-path: chart/

      - name: Echo the Helm Chart Version
        run: echo "chart version is -> ${{ steps.version.outputs.version }}"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Create Chart Package
        run: helm package chart  --version ${{ steps.version.outputs.version }}

      - name: Login to Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | helm registry login ${{ env.REGISTRY_ADDR }} --username ${{ env.REGISTRY_USERNAME }} --password-stdin

      - name: Push Packaged Chart to Registry
        run: helm push helm-charts-oci-proxy-${{ steps.version.outputs.version }}.tgz oci://${{ env.REGISTRY_ADDR }}/library

